### PR TITLE
aio_init is in

### PR DESCRIPTION
**Pull request by fried**
I also am using a hybrid dispatch model to get the results into python since AddPendingCall seems to be a little bit faster than acquiring the GIL. So try AddPendingCall if that fails acquire the gil.

### CODE REVIEW

**Comment by felipecruz** [comment]
I'll merge it manually since it won't be a fast-foward merge! :)

**Comment by fried** [comment]
Oh sorry about that, means I forgot to merge upstream :P

**Comment by felipecruz** [comment]
again... thanks!

you really should get more involved will all python async IO discussion :)

**Comment by fried** [comment]
where is that taking place?

**Comment by felipecruz** [comment]
There are 2(actually 3 but i dont remeber the last one) approaches.. 

EventLoop - like libev, libuv, where you register callbacks with events like `ev.register(fd, ev.READ)`
Coroutine based asyn c- yield when an operation can block, like `yield from read(fd...)`

check this:

http://code.google.com/p/tulip/

a coroutine based experiment by GvR

register in python-ideas
http://mail.python.org/mailman/listinfo/python-ideas

**Pull request merged**
